version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: firstdb
      MYSQL_USER: first
      MYSQL_PASSWORD: first
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql

  springboot-app:
    image: yusejeong/firstmysql
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/firstdb
      SPRING_DATASOURCE_USERNAME: first
      SPRING_DATASOURCE_PASSWORD: first
    networks:
        - springboot-mysql

networks:
  springboot-mysql: